repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: name-tests-test
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: detect-private-key
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "-a", "from __future__ import annotations" ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [ "--py312-plus", "--keep-runtime-typing" ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        args: ["--skip=*.js,*.css,*.map", "-L","collapsable"]
        exclude: "poetry.lock|pyproject.toml"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: python-check-mock-methods
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
