# pyproject.toml

[tool.poetry]
name        = "avtools"
version     = "1.0.5"
description = "Monitoring tools for the AV infrastructure of CERN."
readme      = "README.md"

authors = [
  "jsapinat <jose.bras@cern.ch>",
  "zembrzus <pawel.zembrzuski@cern.ch>",
  "jpolok <jarek.polok@cern.ch>",
]

license    = "Proprietary"
homepage   = "https://gitlab.cern.ch/itdcim/av-tools"
repository = "https://gitlab.cern.ch/itdcim/av-tools.git"

[tool.poetry.urls]
Homepage   = "https://gitlab.cern.ch/itdcim/av-tools"
Repository = "https://gitlab.cern.ch/itdcim/av-tools.git"
Issues     = "https://gitlab.cern.ch/itdcim/av-tools/-/issues"

# Internal PyPI mirror (CERN)
[[tool.poetry.source]]
name     = "pypiserver"
url      = "https://pypiserver.cern.ch/simple"
priority = "supplemental"

[tool.poetry.dependencies]
# Python runtime: 3.11 only, but any microversion (works with RHEL9 python3.11)
python = ">=3.11,<3.12"

# Runtime dependencies (alphabetical)
cern-oauthlib           = ">=23.2.2"
click                   = ">=8.1.7,<9.0.0"
influxdb                = "^5.3.1"
influxdb-client         = "^1.48.0"
pexpect                 = ">=4.8.0,<5.0.0"
psycopg2-binary         = "^2.9.10"
pyasn1                  = ">=0.4.8,<0.5.0"
pydantic                = "^2.10.6"
pysnmp                  = "4.4.12"
requests                = "^2.31.0"
sqlalchemy              = "^2.0.39"
structlog               = "^25.1.0"

[[tool.poetry.packages]]
include = "avtools"
from    = "src"

[tool.poetry.scripts]
# CLI entry points
avtools   = "avtools.main:cli"
get-token = "avtools.main:get_token"

[tool.poetry.group.lint.dependencies]
black          = "^25.1.0"
detect-secrets = "^1.5.0"

[tool.poetry.group.dev.dependencies]
ipdb       = "^0.13.13"
ipython    = "^8.32.0"
pre-commit = "^4.1.0"

[build-system]
requires      = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
