"""Exception re-exports for AV Tools.

This module provides a single import location for AVTools exception types.
"""

from __future__ import annotations

from avtools.exception.errors import (
    AVToolsError,
    AbstractDeviceHandlerError,
    DeviceHandlerFactoryError,
    EAMError,
    EAMDeviceORMError,
    EAMPositionORMError,
    EAMTextSanitizerError,
    InfluxClientError,
    InfluxDataPackageError,
    InfluxError,
    InfluxPackageError,
    InfluxParsableError,
    InfluxSerializableError,
    LanDBError,
    LanDBIPAddressORMError,
    MoreThanOneDeviceFound,
    NoRecordsFound,
    PostgresClientError,
    PostgresInventoryClientError,
    PostgresInventoryORMPackageError,
    PostgresInventoryPackageError,
    PostgresError,
    PostgresMonitoringClientError,
    PostgresMonitoringCodecError,
    PostgresMonitoringModelsPackageError,
    PostgresMonitoringORMPackageError,
    PostgresMonitoringPackageError,
    PostgresORMPackageError,
    PostgresPackageError,
    ProjectorHandlerError,
    ProjectorHandlerFactoryError,
    ProjectorStatsError,
    PipelineError,
    PipelinePackageError,
    SNMPObserverRouterError,
    SNMPClientError,
    SNMPError,
    SNMPFactoriesPackageError,
    SNMPHandlersPackageError,
    SNMPPackageError,
    SNMPQueriesPackageError,
    SNMPQueryExecutionError,
    SNMPQueryRoutingError,
    SNMPQuerySpecError,
    StatsBaseError,
    SyncReportLoggerError,
    TimeSeriesHelperError,
    TimeseriesError,
    TimeseriesEncoderError,
    TimeseriesMetricsError,
    TimeseriesPackageError,
    TimeseriesPublisherError,
    OTLPPublishError,
    UtilsError,
    UtilsPackageError,
)

__all__ = [
    # Legacy
    "EAMError",
    "LanDBError",
    "NoRecordsFound",
    "MoreThanOneDeviceFound",
    # New base types
    "AVToolsError",
    "InfluxError",
    "PostgresError",
    "PipelineError",
    "TimeseriesError",
    "SNMPError",
    "UtilsError",
    # Influx
    "InfluxPackageError",
    "InfluxClientError",
    "InfluxParsableError",
    "InfluxSerializableError",
    "TimeSeriesHelperError",
    "InfluxDataPackageError",
    "StatsBaseError",
    "ProjectorStatsError",
    # Postgres
    "PostgresPackageError",
    "PostgresClientError",
    "PostgresORMPackageError",
    "EAMDeviceORMError",
    "EAMPositionORMError",
    "LanDBIPAddressORMError",
    # Postgres subpackages
    "PostgresInventoryPackageError",
    "PostgresInventoryClientError",
    "PostgresInventoryORMPackageError",
    "PostgresMonitoringPackageError",
    "PostgresMonitoringClientError",
    "PostgresMonitoringCodecError",
    "PostgresMonitoringModelsPackageError",
    "PostgresMonitoringORMPackageError",
    # Pipeline
    "PipelinePackageError",
    "SNMPObserverRouterError",
    # Timeseries
    "TimeseriesPackageError",
    "TimeseriesEncoderError",
    "TimeseriesMetricsError",
    "TimeseriesPublisherError",
    "OTLPPublishError",
    # SNMP
    "SNMPPackageError",
    "SNMPClientError",
    "SNMPFactoriesPackageError",
    "DeviceHandlerFactoryError",
    "ProjectorHandlerFactoryError",
    "SNMPHandlersPackageError",
    "AbstractDeviceHandlerError",
    "ProjectorHandlerError",
    # SNMP queries
    "SNMPQueriesPackageError",
    "SNMPQuerySpecError",
    "SNMPQueryRoutingError",
    "SNMPQueryExecutionError",
    # Utils
    "UtilsPackageError",
    "EAMTextSanitizerError",
    "SyncReportLoggerError",
]
